name: coastal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.*
  - pip>=20
  - adlfs
  - awscli
  - azure-data-tables
  - boto3
  - cartopy
  - cfgrib
  - click
  - dask-cloudprovider
  - azure-identity
  - dask==2022.11.1 # until https://github.com/geopandas/dask-geopandas/pull/230 is merged
  - distributed
  - dask-geopandas
  - dask-ml
  - datacube
  - datashader
  - descartes
  - eccodes>=2.24.2
  - folium
  - fsspec
  - gcsfs
  - geopandas>=0.11.0
  - geoviews
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-xarray
  - ipykernel
  - matplotlib
  - numpy
  - panel
  - pandas
  - planetary-computer
  - pyarrow
  - pyogrio
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - stac-vrt
  - stac-geoparquet
  - stackstac
  - zarr
  - s3fs
  - rasterio
  - mapclassify
  - rioxarray
  - bandit
  - isort
  - black
  - zarr
  - h5py
  - geojson
  - spatialpandas
